<?php // $Id$

define('PDX_SOC_FACEBOOK', 'https://www.facebook.com/NeedTome-996282783743830/');
define('PDX_SOC_TWITTER', 'https://twitter.com/NeedToMe_by');
define('PDX_SOC_VKONTAKTE', 'https://vk.com/needtominsk');
define('PDX_CITY_NAME', 'Минск');
define('PDX_CITY_NAME2', 'Минске');
define('PDX_CITY_ID', 28);
define('PDX_CITY_CREATED', 1447237777);
define('PDX_CITY_COUNTRY', 62);
define('PDX_CITY_SUFFIX', 'mn');
define('PDX_CITY_CUR', 'руб');
define('PDX_CITY_MASK', '+375 (99) 9999999');
define('PDX_PRICE_GOLD', 200);
define('PDX_PRICE_PREMIUM', 20);
define('PDX_PRICE_TOP', 1);
define('PDX_METRIKA_YANDEX', '39250435'); //
define('PDX_TWITTER1', 'tCzrVjLKpglr307WJ1bvmIY05');
define('PDX_TWITTER2', 'gKEcL5HckNlexYl2OU4R66NmynLNm1ZcV1vDif8TU5pbS0VJVS');
define('PDX_TWITTER3', '4364958322-eu3BeJht34jjwvfymfhoP3MJLG0d70q5gvD1ty6');
define('PDX_TWITTER4', 'GH2JEmoMAfmdvL5vXUdH9MqpDQ9ArAtjSI13Q33ExqjTS');
define('PDX_VKONTAKTE', '1');
define('PDX_CONTACTS_PRESS', '375 (25) 907-06-09 (Ирина)');
define('PDX_FIRST_MESSAGE_CONTENT', 170);
define('PDX_JIVOSITE', 'wpUT0RvVSP');
define('PDX_APP_ANDROID', 'https://play.google.com/store/apps/details?id=me.needto.minsk');
define('PDX_APP_IOS', 'https://itunes.apple.com/ru/app/minsk.-arenda-vesej-bez-problem/id1092439548?mt=8');

