<?php // $Id$

define('PDX_SOC_FACEBOOK', '');
define('PDX_SOC_TWITTER', 'https://twitter.com/needtome_od');
define('PDX_SOC_VKONTAKTE', 'https://vk.com/needtoodessa');
define('PDX_CITY_NAME', 'Одесса');
define('PDX_CITY_NAME2', 'Одессе');
define('PDX_CITY_ID', 27);
define('PDX_CITY_CREATED', 1452777777);
define('PDX_CITY_COUNTRY', 61);
define('PDX_CITY_SUFFIX', 'od');
define('PDX_CITY_CUR', 'грн');
define('PDX_CITY_MASK', '+380 (99) 9999999');
define('PDX_PRICE_GOLD', 500);
define('PDX_PRICE_PREMIUM', 50);
define('PDX_PRICE_TOP', 3);
define('PDX_METRIKA_YANDEX', 39250480);
define('PDX_TWITTER1', 'k1iycckdxT6dcjqjseFM4nmwW');
define('PDX_TWITTER2', '09hVahYzy7ZXIdkJuPJMS3rhzEBxmDRZNpuedMzaGMFWy4pME1');
define('PDX_TWITTER3', '4833241569-Su4J2poGwRn6XFysGcDmrFSXJWmJ4nkjzML6Wbt');
define('PDX_TWITTER4', 'nAszxY6wQPYmUrJVL4BzzeLUaiEo8DmD5SnXBeWdYjBwr');
define('PDX_VKONTAKTE', '1');
define('PDX_CONTACTS_PRESS', '+380 (68) 903-82-78 (Юлия)');
define('PDX_FIRST_MESSAGE_CONTENT', 2);
define('PDX_JIVOSITE', 'ytSVBtvcrd');
define('PDX_APP_ANDROID', 'https://play.google.com/store/apps/details?id=me.needto.od');
define('PDX_APP_IOS', 'https://itunes.apple.com/us/app/odessa.-arenda-vesej-bez-problem/id1102317579?l=ru&ls=1&mt=8');
