<?php // $Id$

define('PDX_SOC_FACEBOOK', 'https://www.facebook.com/NeedTome-996282783743830/');
define('PDX_SOC_TWITTER', '');
define('PDX_SOC_VKONTAKTE', '');
define('PDX_CITY_NAME', 'Самара');
define('PDX_CITY_NAME2', 'Самаре');
define('PDX_CITY_ID', 4);
define('PDX_CITY_CREATED', 1473334741);
define('PDX_CITY_COUNTRY', 60);
define('PDX_CITY_SUFFIX', 'smr');
define('PDX_CITY_CUR', 'руб');
define('PDX_CITY_MASK', '+375 (99) 9999999');
define('PDX_PRICE_GOLD', 200);
define('PDX_PRICE_PREMIUM', 20);
define('PDX_PRICE_TOP', 1);
define('PDX_METRIKA_YANDEX', ''); //
define('PDX_TWITTER1', '');
define('PDX_TWITTER2', '');
define('PDX_TWITTER3', '');
define('PDX_TWITTER4', '');
define('PDX_VKONTAKTE', '');
define('PDX_CONTACTS_PRESS', '375 (25) 907-06-09 (Ирина)');
define('PDX_FIRST_MESSAGE_CONTENT', 2);
define('PDX_JIVOSITE', '');
define('PDX_APP_ANDROID', '');
define('PDX_APP_IOS', '');
