<?php // $Id$

define('PDX_SOC_FACEBOOK', '');
define('PDX_SOC_TWITTER', '');
define('PDX_SOC_VKONTAKTE', 'https://vk.com/needtospb');
define('PDX_CITY_NAME', 'Питер');
define('PDX_CITY_NAME2', 'Санкт-Петербурге');
define('PDX_CITY_ID', 26);
define('PDX_CITY_CREATED', 1457977777);
define('PDX_CITY_COUNTRY', 60);
define('PDX_CITY_SUFFIX', 'sp');
define('PDX_CITY_CUR', 'руб');
define('PDX_CITY_MASK', '+7 (999) 9999999');
define('PDX_PRICE_GOLD', 600);
define('PDX_PRICE_PREMIUM', 60);
define('PDX_PRICE_TOP', 3);
define('PDX_METRIKA_YANDEX', 39250520);
define('PDX_TWITTER1', '');
define('PDX_TWITTER2', '');
define('PDX_TWITTER3', '');
define('PDX_TWITTER4', '');
define('PDX_VKONTAKTE', '1'); //114599156
define('PDX_CONTACTS_PRESS', '8 (910) 6005101 (Наталья)');
define('PDX_FIRST_MESSAGE_CONTENT', '2');
define('PDX_JIVOSITE', 'obgyOaDFfY');
define('PDX_APP_ANDROID', 'https://play.google.com/store/apps/details?id=me.needto.sp');
define('PDX_APP_IOS', 'https://itunes.apple.com/us/app/piter.-arenda-vesej-bez-problem/id1102382676?l=ru&ls=1&mt=8');
